roundround:
  versions: <=0.2.0
  commands: echo roundround-a
patterns:
  versions: <=1.0.2
  commands:
    - echo patterns-a
    - echo patterns-b
is-it-weekend:
  node: '4.x || 6.x'
  versions: '1.0.0'
  commands: node --version
